### ISSUE TITLE
Cargo install fails with "Could not find `__rt` in `quote`"

### ISSUE THREAD

**Issue by emk** [marcaddeo/clparse#19]
This looks like a neat tool. Thank you for implementing it!

When I ran `cargo install clparse`, it failed with the following error:

```
error[E0433]: failed to resolve: could not find `__rt` in `quote`
   --> /home/emk/.cargo/registry/src/github.com-1ecc6299db9ec823/err-derive-0.1.6/src/lib.rs:145:63
    |
145 | fn display_body(s: &synstructure::Structure) -> Option<quote::__rt::TokenStream> {
    |                                                               ^^^^ could not find `__rt` in `quote`
```

**Comment by marcaddeo** [comment]
@emk appreciate the interest in the project! I've merged a fix and am pushing out a release shortly.

**Comment by marcaddeo** [comment]
@emk `0.8.1` has been published to crates.io, so you should be able to successfully install with `cargo install clparse` now.

**Comment by emk** [comment]
Excellent! Thank you very much.

I'm using it as follows to extract the release notes for a specific version:

```sh
          clparse -f json CHANGELOG.md | \
            jq ".releases[] | select(.version == \"$RELEASE_VERSION\") | { title: \"\", description: \"\", releases: [.] }" | \
            clparse - | \
            tail -n +3 > RELEASE_BODY.md
```

I'm planning to convert over [`dbcrossbar`](https://www.dbcrossbar.org/) and a bunch of other open source tools to use this snippet to automatically create GitHub release notes from `CHANGELOG.md` files, which is really handy. (I'd be happy to share the finished GitHub CI script once it's ready.)

It might be worth adding a flag like `--extract-version $RELEASE_VERSION` that could be used like:

```sh
clparse --extract-version "$RELEASE_VERSION" CHANGELOG.md > RELEASE_BODY.md
```

But maybe that's out of scope. :-)

**Comment by marcaddeo** [comment]
Hey @emk, glad it's working for you!

I think I'd probably leave that feature out of `clparse` to keep it very simple. The aim of `clparse` is mainly to act as a library, but I figured exposing a cli app for it as well made sense to be able to do exactly what you're doing with it now. I'm doing similar things with it at my day job.

I have another tool that's part of this "suite" of changelog stuff called [`cl`](https://github.com/marcaddeo/cl) that may be a good candidate for adding that feature to, though. However, I'm not sure if it would fit your use case to have that tool in your arsenal. Basically `cl` is an opinionated way of managing the `CHANGELOG.md` file within a team using a CI pipeline to keep things aggregated. However, it does share some similarities obviously. Typing just `cl` will show you the unreleased changes for example and allow you to specify which format to output them as.

I could see adding some sort of way to grab a specific release out of it. I've actually wanted to add that feature.

But yeah, I'm curious if you'd think that's a good solution to the problem and what you think the command should be. Maybe `cl get 1.2.3`? Totally open to suggestions.

P.S.
I'm pretty sure `cl` is going to have the same installation issue you faced with `clparse` when using `cargo install`/installing from source. I need to update it still.
